<a href="https://colab.research.google.com/github/arangates/funda/blob/main/funda_scraper_example_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install funda-scraper

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting funda-scraper
  Downloading funda_scraper-0.0.2-py3-none-any.whl (9.1 kB)
Requirement already satisfied: beautifulsoup4>=4.8 in /usr/local/lib/python3.10/dist-packages (from funda-scraper) (4.11.2)
Requirement already satisfied: requests>=2 in /usr/local/lib/python3.10/dist-packages (from funda-scraper) (2.27.1)
Collecting diot>=0.1.5 (from funda-scraper)
  Downloading diot-0.1.8-py3-none-any.whl (11 kB)
Requirement already satisfied: PyYAML>=5.0 in /usr/local/lib/python3.10/dist-packages (from funda-scraper) (6.0)
Requirement already satisfied: tqdm>=4.42.0 in /usr/local/lib/python3.10/dist-packages (from funda-scraper) (4.65.0)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.10/dist-packages (from funda-scraper) (1.5.3)
Requirement already satisfied: lxml>=4 in /usr/local/lib/python3.10/dist-packages (from funda-scraper) (4.9.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.8->funda-scraper) (2.4.1)
Collecting inflection<0.6,>=0.5 (from diot>=0.1.5->funda-scraper)
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->funda-scraper) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->funda-scraper) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->funda-scraper) (1.22.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2->funda-scraper) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2->funda-scraper) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2->funda-scraper) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2->funda-scraper) (3.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.2->funda-scraper) (1.16.0)
Installing collected packages: inflection, diot, funda-scraper
Successfully installed diot-0.1.8 funda-scraper-0.0.2 inflection-0.5.1

In [3]:
from funda_scraper import FundaScraper

scraper = FundaScraper(area="eindhoven", want_to="buy", find_past=False, n_pages=1)
scraper

FundaScraper(area=eindhoven, want_to=buy, n_pages=1, use_past_data=False)

In [4]:
df = scraper.run()

2023-06-14 08:52:05,623 - INFO - *** Phase 1: Fetch all the available links from all pages ***  (scrape.py:107)
INFO:funda_scraper:*** Phase 1: Fetch all the available links from all pages ***
100%|██████████| 2/2 [00:02<00:00,  1.34s/it]
2023-06-14 08:52:08,332 - INFO - *** Got all the urls. 15 houses found in 1 pages. *** (scrape.py:118)
INFO:funda_scraper:*** Got all the urls. 15 houses found in 1 pages. ***
2023-06-14 08:52:08,337 - INFO - *** Phase 2: Start scraping results from individual links *** (scrape.py:183)
INFO:funda_scraper:*** Phase 2: Start scraping results from individual links ***

  0%|          | 0/15 [00:00<?, ?it/s]

2023-06-14 08:52:27,798 - INFO - *** All scraping done: 15 results *** (scrape.py:195)
INFO:funda_scraper:*** All scraping done: 15 results ***
2023-06-14 08:52:27,806 - INFO - *** Cleaning data *** (scrape.py:229)
INFO:funda_scraper:*** Cleaning data ***

In [5]:
df.head()

,house_id,city,house_type,building_type,price,price_m2,room,bedroom,bathroom,living_area,...,has_balcony,has_garden,zip,address,year_built,house_age,date_list,ym_list,year_list,descrip
0,42131180,eindhoven,huis,Resale property,425000,3663.8,4,3,1,116,...,0,1,5627,Tullelaan 2,1985,38,2023-06-09,2023-06-01,2023,\r\nNieuw in de verkoop bij Tim de Rouw: G...
1,42146242,eindhoven,huis,Resale property,495000,4230.8,5,4,1,117,...,0,1,5658,Waterlinie 125,2020,3,2023-06-12,2023-06-01,2023,\r\nDeze recent gebouwde woning in Waterrijk...
2,42132260,eindhoven,huis,Resale property,499000,3261.4,6,4,1,153,...,0,1,5653,Zuidewijn 38,1975,48,2023-06-09,2023-06-01,2023,\r\nNieuw in de verkoop bij Tim de Rouw: Z...
3,42132412,eindhoven,huis,Resale property,850000,5000.0,7,4,1,170,...,0,1,5644,Schweitzerlaan 48,1977,46,2023-06-08,2023-06-01,2023,\r\nENGLISH TRANSLATION BELOW Maandag 12 jun...
4,42145206,eindhoven,huis,Resale property,369000,3208.7,6,4,1,115,...,0,1,5622,Barrierweg 204,1931,92,2023-06-09,2023-06-01,2023,\r\nWonen in een gezellig gemeentelijk monum...

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [6]:
scraper.save_csv(df)

2023-06-14 08:52:49,627 - INFO - *** File saved: ./data/houseprice_20230614_eindhoven_selling_15.csv. *** (scrape.py:217)
INFO:funda_scraper:*** File saved: ./data/houseprice_20230614_eindhoven_selling_15.csv. ***

In [7]:
scraper.clean_df.head(1)

,house_id,city,house_type,building_type,price,price_m2,room,bedroom,bathroom,living_area,...,has_balcony,has_garden,zip,address,year_built,house_age,date_list,ym_list,year_list,descrip
0,42131180,eindhoven,huis,Resale property,425000,3663.8,4,3,1,116,...,0,1,5627,Tullelaan 2,1985,38,2023-06-09,2023-06-01,2023,\r\nNieuw in de verkoop bij Tim de Rouw: G...

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
scraper.raw_df.head(1)

,url,price,address,descrip,listed_since,zip_code,size,year,living_area,kind_of_house,...,parking,neighborhood_name,date_list,date_sold,term,price_sold,last_ask_price,last_ask_price_m2,city,log_id
0,https://www.funda.nl/en/huur/amsterdam/apparte...,"€ 2,400 p/mo.",Marie Heinekenplein 102,"\r\nVERY LUXURY, 3-ROOM APARTMENT OF 105 M2...",Today,1072 MK Amsterdam\r,105 m²,1995,105 m²,Upstairs apartment (apartment),...,\nRegistration with KvK\n\nYes\n\nAnnual meeti...,na,"€ 2,400 per month (none service charges)\r\n ...",\nResale property\n,\n1995\n\n\n,na,"€ 2,400 per month (none service charges)\r ...",na,amsterdam,202209-1711-4052

In [8]:
scraper.links

['https://www.funda.nl/en/koop/eindhoven/huis-42131180-tullelaan-2/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42146242-waterlinie-125/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42132260-zuidewijn-38/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42132412-schweitzerlaan-48/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42145206-barrierweg-204/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42146654-zomereik-26/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42146038-chet-bakerlaan-6/',
 'https://www.funda.nl/en/koop/eindhoven/huis-88598052-salvador-allendestraat-5/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42147852-kalverstraat-46/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42145013-generaal-de-gaullelaan-15/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42145061-vrijkensven-2/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42145288-planetenlaan-8/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42148044-serlioweg-18/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42145019-finisterelaan-55/',
 'https://www.funda.nl/en/koop/eindhoven/huis-42147259-molierelaan-100/']